baseURL = "https://chuzzl3wit.github.io/"
languageCode = "en-us"
title = "James' Test Site"
theme = "ananke"
publishDir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/logo.jpg"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCP8E5qQ47j5hnx77jSlPTDw"
  github = "https://github.com/chuzzl3wit"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/smile.jpg"
  recent_posts_number = 2
